version: "3.9"

services: 
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: visits
    volumes:
      - node-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-compose-api
    ports:
      - "3000:3000"      
    depends_on:
      db:
        condition: service_healthy
    command: node index.js

volumes:
  node-volume: 